### PR TITLE
ENHANCEMENT additional filter options

### PR DESCRIPTION
**Pull request by muskie9**
Add ability to utilize `filterAny()` and `filterByCallback()`

### CODE REVIEW

**Comment by g4b0** [comment]
For backward compatibility maybe it can be good to check if method_exists also for getSearchFilterAny, what do you think about it?

**Comment by muskie9** [comment]
Good point, I've updated my PR to check if `getSearchFilterAny` exists on the class being queried.

**Comment by g4b0** [comment]
Good work!

**Comment by muskie9** [comment]
Cheers!

**Pull request merged**
