### PR TITLE
Upgrade to SS4

### PR DESCRIPTION
**Pull request by antons-**
First of all, thanks alot for writing this module.

Our web agency maintains a modified fork of your module. As we need our version of the module to be SS4 compatible I thought I'd PR this back to the original.

I'm using SS 4.1 to build this.

Some notes about the upgrade:
* Moved the `code` folder to `src` to match the SS4 module standards
* Updated composer.json to SS4. It may work with SS3 but I haven't tested this.
* I've added namespacing to all classes (assummed `Zirak/SearchableDataObjects` would be fine here but this can be changed)
* Updated any code that broke due to changes with the SS4 API
* Instead of dropping the `SearchableDataObjects` table, I truncate it. Notes here https://github.com/g4b0/silverstripe-searchable-dataobjects/commit/ae4a0d8edfb07346e60c52c24f754c1b36342cec
* Tests do not work in SS 4.1 - I believe this bug is to blame https://github.com/silverstripe/silverstripe-framework/issues/7978. Once this is fixed the tests will need to be looked at again.
* `FulltextSearchable::enable()` adds the `ContentControllerSearchExtension` extension and overrides your `CustomSearch` extension. I've gotten around this but wonder if there is a better way of doing this. Notes here https://github.com/g4b0/silverstripe-searchable-dataobjects/commit/bd5de0ba1160f6f37b0dda25c00fbad8952d7d89
* This code also references a namespaced `HTMLPurifier` - I can add another PR in your other repo if you want.

The other thing I noticed in my testing was the `PageId` column in `SearchableDataObjects` was always `0`. Not sure if this is correct?

Happy to make any changes you want. Thanks!

### CODE REVIEW

**Comment by g4b0** [comment]
Hi,
I'm really happy to merge your PR, I will start a new major 5.x version for SS 4.x compatibility.
Just a small change: I was planning to change package name from zirak/searchable-dataobjects to g4b0/searchable-dataobjects, in order to have the same name in github and packagist.
Since it'a a composer compatibility break I think that it's good to do it during major version change.

Can you please change namespacing in g4b0/SearchableDataObjects and add it to this PR? 

I will do the rest in composer.json.

Thanks a lot for your work

**Comment by antons-** [comment]
I've updated the namespace to `g4b0\SearchableDataObjects` 😃 

Also I have found a bug that prevents dataobjects from updating the `SearchableDataObjects` on save here https://github.com/antons-/silverstripe-searchable-dataobjects/blob/a0c948e05a284eb310cd487250dcf331103e0aa9/src/SearchableDataObject.php#L40 - something to do with the namespaces and table names I suspect. I'll take another look over the next few days.

**Comment by g4b0** [comment]
Ok, thanks. I will wait for merging :)

**Comment by antons-** [comment]
Tested and all fixed now, it didn't take as long as I thought it would to fix.

Also, I forgot to change this to a `silverstripe-vendormodule` in the `composer.json` but I'll leave this to you :)

**Pull request merged**
