### PR TITLE
Use ORM to create field specs

### PR DESCRIPTION
**Pull request by rotassator**
Use the DB connector to define the field specs so collation settings are included.

* the fixed ID field spec was left as is (unsigned) but could be reviewed in the future

### CODE REVIEW

**Comment by ntd** [comment]
Hi Steve,

it's a shame `createTable` cannot be used... it would be much more convenient.

I'd quote field and table names anyway, just to be consistent with the rest of the codebase, e.g.:

    '"ID" int(10) ' . $unsigned . ' NOT NULL,',
    '"ClassName" ' . $connection->varchar(['precision' => 255]) . ',',
    '"Title" ' . $connection->varchar(['precision' => 255]) . ' NOT NULL,',
    ...

In any case this should fix #33.

**Comment by g4b0** [comment]
Good work @rotassator and @ntd 
@rotassator could you please include @ntd suggestion in your PR, in order to have all fields defined in a consistent way?

**Comment by rotassator** [comment]
OK, I've quoted the field and table names in the SQL command strings. I also improved the ORM calls to fix an issue between SilverStripe 3.1 and 3.2+ versions.

**Comment by g4b0** [comment]
Nice work @rotassator !

**Comment by g4b0** [comment]
Just for information, I've created a new tag 3.0 
I've decided to upgrade the major version, since the underlying db is slightly changed

**Pull request merged**
